{% set name = "snapshottest" %}
{% set version = "0.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cc7157e77674ea8ebeb2351466ff50cd4b5ad8e213adc06df9c16a75ab5bafc

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six >=1.10.0
    - termcolor

test:
  requires:
    - django
    - nose
    - pytest

  imports:
    - snapshottest
    - snapshottest.django
    - snapshottest.nose
    - snapshottest.pytest

about:
  home: https://github.com/syrusakbary/snapshottest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Snapshot Testing utils for Python'

  # The remaining entries in this section are optional, but recommended
  description: |
    Snapshot testing is a way to test your APIs without writing actual test cases.

      1. A snapshot is a single state of your API, saved in a file.
      2. You have a set of snapshots for your API endpoints.
      3. Once you add a new feature, you can generate automatically new snapshots
         for the updated API.

extra:
  recipe-maintainers:
    - bollwyvl
