travis:
  secure:
    BINSTAR_TOKEN: BrqosjVntmP8+xR6fmIOpB7tc2upyZ7M634XoW5A91zJiUWuIVqvy7rY9hat88bxcVLW+5Cr/jZcsSLtVBIxr5j9e87/ew4RTz+Egc+I23TYx1iMTbGuZ/uT/7El2B3mpo3XX9LN91NMLD+FOP3tS2I8S8y+nV1ra74HWcX4/ifOTA0/weNkPA05CXrG9gK9Xm5d7SyNcI94QXeAh4RyY0omIdxxbAmOXrm4KP5f0tZ4PmLQShTwzuyKRvSDEU/eWuaTY2XdxrNPCWKCgbGRCcrkDWdGh73FZ+bRDyq0Y0qEaxq1gEH8sDNTENcyF02Yy+wCRG99MY0P1Bjsz4qfIShT85vXV5BcEtD0TCWs3IQh8SfJeMthqsMphAqoonqFQV0A6aoFQXmAK/Au+rvDfn2mLClkH0khguY7ErANIGOZ0S3UpNFjqtffa+ZFWZc1sL19hWPJVCIs9AGM5hqSSLxhljhG2r1T0FLSYH+IIRExYsSYHdk4KiADjg2kICaiM3hBpYsWDNktbumx7Yv5CCgJf8CoRulal/Jq5jgZ7+DC16ZsjoP+yfY0RcD+4xdOwLCuMsKBsq8owdiA+6onrX7S74k9VmElqVVcUPa+rJbDQombv3WhndJ4+OB6+6fcQb5FO/BU1VeL1bkskr75tqxD4S1R7EqEg1SJnbx+bjA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
